# -*- coding: utf-8 -*-
"""251121cjh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dD_4ofjEB9OVStDxXd659okxjqkez61X
"""

from textblob import TextBlob

review = "This movie was terrible! The acting was poor and the story was boring."
sentiment = TextBlob(review).sentiment.polarity
print(f"입력={review}\n")

if sentiment > 0:
  print("결과=긍정적")
elif sentiment ==0:
  print("결과=중립적")
elif sentiment < 0:
  print("결과=부정적")

f=open('wikiAi.txt','r',encoding='UTF-8')
text = f.read()
print(text)

from wordcloud import WordCloud
import matplotlib.pyplot as plt
from wordcloud import STOPWORDS
from PIL import Image
import numpy as np

wc = WordCloud(width=1500,height=1200)
wc.generate(text)
plt.imshow(wc)
plt.show()

불용어 = STOPWORDS.union({'goals','field','human','see'})
wc = WordCloud(width=1500,height=1200, stopwords = 불용어, background_color='white')
wc.generate(text)
plt.imshow(wc)
plt.show()

불용어 = STOPWORDS.union({'goals','field','human','see'})
wc = WordCloud(width=1500,height=1200, stopwords = 불용어, background_color='white')
wc.generate(text)
plt.imshow(wc)
plt.axis('off')
plt.show()

불용어 = STOPWORDS.union({'goals','field','human','see'})
maskStar = np.array(Image.open('/content/star.png'))
wc = WordCloud(width=1500,height=1200, stopwords = 불용어, background_color='white', mask=maskStar)
wc.generate(text)
plt.imshow(wc)
plt.axis('off')
plt.show()
wc.to_file('oud_directmy_wordcl.png')

import re
text = "이번 학기 개설 과목은 CS101입니다."
match = re.search('[A-Za-z]{2}\d{3}',text)
if match:
  print("과목 코드가 발견됨:", match)
else:
  print("과목 코드가 발견되지 않음:",match)

string = "My phone number is 010-1234-5678. Call me anytime."
result = re.search('\d{3}-\d{4}-\d{4}', string)
print(result.group())

text = 'There are 12 apples and 3 organes'
numbers = re.findall('\d+',text)
print(numbers)

def is_valid_jumin(st):
  pattern = '^\d{6}\-\d{7}'
  match = re.match(pattern,st)
  return match

jumin = input('당신의 주민등록번호는: ')
if is_valid_jumin(jumin):
  print('주민등록번호가 유효합니다.')
else:
  print('주민등록번호가 유효하지 않습니다.')

text = 'abc123def456'
result = re.sub('\d','',text)
print(result)

