# -*- coding: utf-8 -*-
"""CJH251114.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSuKbhdQgZc_reBbKDgYoLKAuAEQdjEf
"""

s = 'Welcome to Python'
s.split()

s = '2025.11.14'
s.split('.')

','.join(['apple', 'grape', 'banana'])

'-'.join('010.1234.5678'.split('.'))

s = 'www.booksr.co.kr'
s.count('.')

s = 'Hello World!'
s.startswith("Hello")

s = 'Hello World!'
s.lower()

s = 'Hello World!'
s.upper()

s = 'Hello World!'
s.replace("World","Python")

s = 'Hello World!'
s.replace('!','')

s = '   Hello World!   '
s.strip()

s = '   Hello World!   '
s.lstrip()

s = '   Hello World!   '
s.rstrip()

s = '##########this is an example###########'
s.strip('#')

s = '##########this is an example###########'
s.lstrip('#')

s = '##########this is an example###########'
s.rstrip('#')

s = 'www.booksr.co.kr'
s.find('.kr')

s = 'www.booksr.co.kr'
s.find('x')

s = 'www.booksr.co.kr'
n = s.index('b')
print('s의 b 인덱스 = ', n)

s = 'www.booksr.co.kr'
n = s.index('b')
print(f's의 b 인덱스 = {n}')

s1 = 'print \n in my string'
print(s1)

#텍스트 처리
s = 'This movie was terrible! The acting was poor and the story was boring.'
words = s.split(' ')

print(f's={s}')
print(f'\n글자수={len(s)}')
print(f'단어들의 리스트={words}')
print(f'단어 수={len(words)}')
print(f'평균 단어 길이={sum(len(word)for word in words)/len(words)}')

#
text='This is an example of removing stop words from a string.'

stop_words = ['is','and','the', 'a', 'an','in','of','to']
words = text.split(' ')

filtered_setece = [word for word in words if word.lower() not in stop_words]
print(f'입력={text}')
print(f'출력={' '.join(filtered_setece)}')

s='the quick brown fox jumps over the lazy dog.'
print(f'입력={s}')

counter = {}
words = s.split()
for word in words:
  if word in counter:
    counter[word] +=1
  else:
    counter[word] = 1
print(f"출력={counter}")

from collections import Counter
s='the quick brown fox jumps over the lazy dog.'
print(f'입력={s}')
words = s.split()

frequency = Counter(words)
print(f"출력={frequency}")

